travis: update config
prasadtalasila/IRCLogParser pull request #220
Opened 2017-12-21 14:19 UTC by kaushik-rohit

## What? Why?
Fix #212 

Changes proposed in this pull request:
- update email recipients
- comment sfood and mprof

## Checks
- [ ] Single commit and [No merge commits](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [ ] Make sure you have added required documentation
- [ ] If you have refactored a code, make sure that you have compared the outputs pre and post refactoring. Add both pre and post refaoring screenshots below if the output is visual

## Any images?

## Notify reviewers
@rohangoel96

2017-12-21 14:23 UTC, prasadtalasila commented
@kaushik-rohit can you also address #219 with this PR?

2017-12-21 14:31 UTC, kaushik-rohit commented
Sure, will do that.

2017-12-23 07:32 UTC, kaushik-rohit commented
@prasadtalasila updated with changes required in #219

2017-12-23 08:13 UTC, prasadtalasila requested changes
@kaushik-rohit 
A few edits in the README.md; travis config looks good.

2017-12-23 08:13 UTC, prasadtalasila commented on README.md
> +The documentation is auto-generated from the commits made on the [dev](https://github.com/prasadtalasila/IRCLogParser/tree/dev) branch. The documentation corresponding to the latest commit on dev bra
How about rephrasing

The documentation corresponding to the latest commit on dev branch is hosted here.

to 

Please see the [online documentation](prasad.talasila.in/IRCLogParser).

2017-12-23 08:13 UTC, prasadtalasila commented on README.md
>  The documentation is deployed on the branch `gh-pages` who's updation has been made automatic by the a [bash script](./ext/docs_auto_deploy.sh) which otherwise requires to run `make html` in docs dir
remove this line and also line-23.

2017-12-23 08:13 UTC, prasadtalasila commented on README.md
> +
```bash
$git clone https://github.com/prasadtalasila/IRCLogParser.git
$cd IRCLogParser
$bash script/install
```

2017-12-23 08:13 UTC, prasadtalasila commented on README.md
> +To run the all the tests locally on your machine, run `python -m unittest -v discover -s test/` in the root directory.
In the next two lines, separate the commands into code snippets.

Ex: To run the all the tests locally on your machine, run
```bash
python -m unittest -v discover -s test/
```
Placing the commands separately reduces errors in copy-paste process.

2017-12-23 08:13 UTC, prasadtalasila commented on README.md
> +The library's working has been modularised into many modules namely input, analysis, output, visualisation and validation. The [sample.py file](./sample.py) very comprehensively presents how one can
Please provide a shell command below this line.

2017-12-23 17:20 UTC, prasadtalasila approved these changes

2017-12-23 17:21 UTC, merged