move validation function from ubuntu.py to validate.py
prasadtalasila/IRCLogParser pull request #222
Opened 2017-12-27 10:03 UTC by kaushik-rohit

## What? Why?
Fix # . (Add Reference to the issue if any)

Changes proposed in this pull request:
- a
- b

## Checks
- [ ] Single commit and [No merge commits](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [ ] Make sure you have added required documentation
- [ ] If you have refactored a code, make sure that you have compared the outputs pre and post refactoring. Add both pre and post refaoring screenshots below if the output is visual

## Any images?

## Notify reviewers
@rohangoel96

2017-12-27 11:45 UTC, prasadtalasila requested changes
@kaushik-rohit please add the unit tests for validate.py.

2017-12-27 11:45 UTC, prasadtalasila commented on lib/validate.py
> +def box_plot_for_degree(log_directory, output_directory, channel_name):
It's better to make a list parameter for channel names and iterste over the list. Right now, the list is static.

2017-12-27 11:45 UTC, prasadtalasila commented on lib/validate.py
> +    for channel_name_iter in [["#kubuntu-devel"], ["#ubuntu-devel"], ["#kubuntu"]]:
Please change the list from static, fixed one to the list coming in via function parameter.

2017-12-27 11:48 UTC, prasadtalasila commented
@kaushik-rohit This being a light PR, it might br better to put in the modifications required for separaring the unit and functional tests in travis.

2017-12-28 20:22 UTC, kaushik-rohit commented
@prasadtalasila fixed. With unit-test and functional test having separate coverage run, out code coverage will decrease (60%) also there are certain codeclimate issues due to moving of code from ubuntu.py (not monitored file) to validate.py. We can take this up in refactoring phase.

2017-12-29 02:01 UTC, prasadtalasila commented
@kaushik-rohit The decrease in coverage is expected. There is a problem in travis.yml. The coverage report is not being uploaded to codeclimate. You can check the end of the log. codeclimate test reporter fails silently.

2017-12-29 06:37 UTC, kaushik-rohit commented
@prasadtalasila That is not an error the token ($CODECLIMATE_REPO_TOKEN) is not exposed in pull requests. Once the pull request is merged it should worked correctly.

2017-12-29 10:40 UTC, merged