Enables cache and parallel builds for tests
prasadtalasila/IRCLogParser pull request #262
Opened 2018-02-12 18:03 UTC by bhuvangupta008

## What? Why?
Fix #211  . (Add Reference to the issue if any)

Changes proposed in this pull request:
- a Enabled Cache for pip packages
- b Build matrix(Unit test, Functional test, Integration test)

## Notify reviewers
@kaushik-rohit
@prasadtalasila

2018-02-13 06:54 UTC, prasadtalasila requested changes
@bhuvangupta008 please see the suggestions.

2018-02-13 06:54 UTC, prasadtalasila commented on .travis.yml
> +  - bash ext/doc_auto_deploy.sh
With the current structure, the doc_auto_deploy.sh is running in all the runs of the build matrix. A better solution is to mix the build stages with build matrix. Please see [example here](https://docs.travis-ci.com/user/build-stages/matrix-expansion/). The `bash ext/doc_auto_deploy.sh` command can be pushed to deploy stage. The default stage would be a test stage (this fact is also exploited in the example given).

2018-02-13 20:40 UTC, bhuvangupta008 commented on .travis.yml
> +  - bash ext/doc_auto_deploy.sh
Sir, if we do the same as inside example and deploy is pushed to a separate stage, then a new VM is created and all the dependency installations are completed. i've pushed the commit already. you can have a view of the travis build. If this is fine, we can go ahead and merge but this deployment then got its's own 4.5 minute setup time thus pushing the total time to 15 mins.

2018-02-13 20:53 UTC, prasadtalasila commented
@bhuvangupta008 In that case, lets keep the docs deployment in unit tests. That should reduce the build time to 8 minutes.

After all of this work, the build time goes down by only 1 minute for now. But as we add more functional and integration tests, the benefits become apparent.

2018-02-14 06:35 UTC, bhuvangupta008 commented
@prasadtalasila, done sir.

2018-02-14 06:35 UTC, prasadtalasila approved these changes

2018-02-14 06:37 UTC, merged