add integration tests for network module
prasadtalasila/IRCLogParser pull request #291
Opened 2018-02-25 18:39 UTC by kaushik-rohit

Integration tests for:-
   1) lib.analysis.network.degree_node_number_csv()
   2) lib.analysis.network.identify_hubs_and_experts()
   3) lib.analysis.network.message_number_graph()
   4) lib.analysis.network.message_number_bins_csv()
   5) lib.analysis.network.message_time_graph()

Issue Link: https://github.com/prasadtalasila/IRCLogParser/issues/280

## What? Why?
Fix #280 

## Checks
- [ ] Single commit and [No merge commits](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [ ] Make sure you have added required documentation
- [ ] If you have refactored a code, make sure that you have compared the outputs pre and post refactoring. Add both pre and post refaoring screenshots below if the output is visual

## Any images?

## Notify reviewers
@kaushik-rohit
@prasadtalasila

2018-02-26 05:55 UTC, prasadtalasila commented
@kaushik-rohit all the expected variables need to have `expected_` as a prefix. Please enforce the same in the unit tests of network.py module as well.

2018-03-01 18:34 UTC, kaushik-rohit commented
@prasadtalasila The work is complete now. You can review/merge it.

2018-03-02 02:30 UTC, prasadtalasila requested changes
@kaushik-rohit please make minor changes to variable names.

2018-03-02 02:30 UTC, prasadtalasila commented on test/integration-test/test_lib/test_analysis/test_network.py
> +        ret = network.message_number_graph(self.log_data, self.nicks, self.nick_same_list, DAY_BY_DAY_ANALYSIS=True)
it is better to name the `ret` as `graph`.

2018-03-02 02:30 UTC, prasadtalasila commented on test/integration-test/test_lib/test_analysis/test_network.py
> +        ret = network.message_time_graph(self.log_data, self.nicks, self.nick_same_list, DAY_BY_DAY_ANALYSIS=False)
It is better to name this variable as `msg_time_aggr_graph`

2018-03-06 09:27 UTC, prasadtalasila approved these changes

2018-03-06 09:28 UTC, merged