User Tracking
prasadtalasila/IRCLogParser pull request #302
Opened 2018-03-17 18:56 UTC by Kausam

## What? Why?
Fix #298  . (Add Reference to the issue if any)

Changes proposed in this pull request:
- add functional test for user tracking

## Checks
- [ ] Single commit and [No merge commits](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [ ] Make sure you have added required documentation
- [ ] If you have refactored a code, make sure that you have compared the outputs pre and post refactoring. Add both pre and post refaoring screenshots below if the output is visual

## Any images?

## Notify reviewers
@kaushik-rohit
@prasadtalasila

2018-03-18 06:55 UTC, kaushik-rohit commented
@prasadtalasila @Kausam The PR looks good to me. Only one thing, some of the tests are already there in test_functional.py and might need to be removed.

2018-03-18 19:01 UTC, prasadtalasila requested changes
@Kausam please see the requested changes. Also as mentioned by @kaushik-rohit , if there is a similar test in [test_functional.py](https://github.com/prasadtalasila/IRCLogParser/blob/master/test/functional-test/test_functional.py), then the code should be removed from [test_functional.py](https://github.com/prasadtalasila/IRCLogParser/blob/master/test/functional-test/test_functional.py)

2018-03-18 19:01 UTC, prasadtalasila commented on test/functional-test/data/output/2013/01/network/degree_node_number_csv/in_degree
> +(lp0
do we need these data files? Can't we reuse the existing data files in tests/data?

2018-03-18 19:01 UTC, prasadtalasila commented on test/functional-test/test_userprofile.py
> +class UserTrackingFunctionalTest(unittest.TestCase):
As mentioned in issue #298, we only need two functional tests here. One for user to channel tracking and another is to user nick change graph. The test functions of network module do not belong here.

2018-03-21 05:21 UTC, prasadtalasila commented
@Kausam you are partially correct on having HITS test in user tracking. As per the paper, Fig 11 (page 19), TF-IDF vs HITS comparison is part of user profile.

2018-03-23 11:25 UTC, prasadtalasila requested changes
@Kausam please see the requested changes. Where possible, the existing test data must be reused.

2018-03-23 11:25 UTC, prasadtalasila commented on test/functional-test/test_userprofile.py
> +class UserTrackingFunctionalTest(unittest.TestCase):
Can we change the class name to "UserProfileTest"

2018-03-23 11:25 UTC, prasadtalasila commented on test/functional-test/test_userprofile.py
> +
assertions section is missing in this test.

2018-03-23 16:45 UTC, prasadtalasila approved these changes

2018-03-23 16:46 UTC, merged